[project]
name = "simple-tts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "edge-tts>=7.2.7",
    "pygame>=2.6.1",
    "pypdf>=6.4.1",
]
